---
title: "LLMs for corpus annotation: Close and extended replications of Morin & Marttinen Larsson (2025) using smaller open LLMs and BERT"
format: pdf
bibliography: references.bib
csl: unified-style-sheet-for-linguistics.csl
editor: 
  markdown: 
    wrap: 72
---

Large Language Models (LLMs) are increasingly being leveraged for the
annotation of large corpora. In an early evaluation of such an
application, @morin2025 presented "a replicable method for automating
grammatical annotation" using Anthropic's model Claude 3.5 Sonnet
[@morin2025: 4]. Their annotation pipeline consisted of a complex
"conversation" with the model over several iterative phases of training
and testing. They were able to achieve an accuracy of 93% compared to
the gold standard provided by a human annotator [@morin2025: 6] and
conclude that the pipeline may also be effective for other linguistic
tasks in other languages [@morin2025: 7].

We aimed to repeat @morin2025's "replicable method" as closely as
possible, using the same data, albeit with two open LLMs, Mistral Small
3.2 24B Instruct [@mistralai2026] and OpenAI GPT OSS 120B [@openai2026].
While the smaller Mistral model did not perform as well on the task
(accuracy of 67%), the open GPT model yielded very similar results
(accuracy of 94%). Although the authors published their data and a full
transcript of their "conversation" with the model [@morin2024], we found
that essential information to independently replicate the study (e.g.,
whether the web interface or an API was used, analysis code, etc.) was
missing - forcing us to make some educated guesses as to the exact
procedure. Our results suggest that, as of early 2026, large commercial
LLMs may not be necessary to complete this kind of linguistic task in
contemporary English.

Next, we tested the need for the extensive 'in-conversation' training
process outlined in @morin2025. To this end, we conducted a second,
extended replication applying a much simpler few-shot training approach
with the best-performing open LLM from our first replication. Our
results suggest that the training process need not be as elaborate as in
@morin2025 to accomplish similarly high accuracy rates.

Finally, we replicated the annotation study using a fine-tuned
DistilBERT model [@sanh]. Although this encoder-only transformer is
considerably smaller than even a small generative LLM, it performed
approximately on par with the 24B Mistral model used in our first
replication. These findings indicate that task-specific supervised
models may provide a competitive and certainly more computationally
efficient alternative to generative LLMs.

Our results have important implications for the replicability of
corpus-linguistic research involving LLMs as part of the annotation
process. We argue that, when choosing a method, issues around model
accessibility, data leakage, and carbon footprint can and should be
taken into consideration.

# References
