---
title: "Using (open) LLMs for linguistic annotation tasks: Replication of a study by Morin & Marttinen Larsson (2025)"
author: Hannah Boxleitner
format: html
bibliography: references.bib
---

# Introduction

In the last decades, researchers in corpus linguistics have gained access to increasingly massive corpora of natural language in different languages. This poses great opportunities, but also necessitates manual cleaning and processing of large amounts of data [@morin2025: 1]. The rise of large language models (LLMs) is therefore a rather interesting development for corpus linguistic research, making it possible to handle larger datasets and corpora automatically. In recent years, a rising number of papers testing LLMs for assisting in linguistic research have been published **(sources)**.

I aim to replicate a study by @morin2025, which presents a replicable method for leveraging LLMs for assistance in linguistic grammatical annotation. While the study was conducted with the model Claude Sonnet 3.5, I will attempt to replicate their methodological pipeline using the same data, but with two open LLMs in R.

This project aims to embody the principles of open science in two respects: First, I want to support the use and examination of open LLMs for analysis of linguistic data. While closed LLMs are now commonly used in day-to-day life, their usage brings difficulties regarding data rights and privacy, **(see presentation for citation)** among others. Many open alternatives are on the rise, but seem to be not as widely used and investigated in studies as necessary **(source?)**. Generalizability considering open models is therefore a relevant concern, especially in relation to open science. **Second**, I want to conduct a replication study and thereby contribute to the central aim of making linguistic research more cumulative and robust. The study was pre-registered before conducting the analysis at OSF [@boxleitner2026]. **??**

**overview??**

# Methodological approach??

During planning and preparation of this replication, I used the handbook by @röseler2025 as a guide for the research process. On a general note, the following steps are listed for a replication:

-   choosing a target study,

-   deciding between different types of replications,

-   planning and running the new study,

-   analyzing the results,

-   discussing outcomes in the light of potential differences,

-   and publishing a report [@röseler2025].

My approach presented in this paper was oriented towards these steps.

# The target study

This study aims to replicate the analysis published in:

> Morin, Cameron, and Matti Marttinen Larsson. 2025. “Large Corpora and Large Language Models: A Replicable Method for Automating Grammatical Annotation.” *Linguistics Vanguard* 11 (1): 501–10. <https://doi/10.1515/lingvan-2024-0228>.

The target study by @morin2025 focuses on the verb *consider*, which can be found in a number of larger grammatical constructions, one of which is an evaluative use, introducing an evaluation or judgement.

**insert screenshots p. 2**

The relationship between the three variants is unclear and it has been suggested that the *consider + as* construction might be becoming less and less common. Searching for this construction in the EnTenTen21 corpus (**source**), the authors encountered the problem that the evaluative construction coexists with another prominent use of consider as a cognition verb **(include example?)**, and out of a random sample of 200 CONSIDER tokens, only 11.5% were found to be true positives and therefore of interest for the research question [@morin2025: 2]. For a corpus-based study addressing this methodological challenge, @morin2025 make use of LLMs for cleaning and annotation tasks, and outline how to automatically annotate large quantities of evaluative *consider* constructions, based on the key processes of prompt engineering, training, and evaluation. For this task, the LLM Claude Sonnet 3.5 and data from the NOW corpus ans Sketch Engine's EnTenTen21 corpus was used [@morin2025: 3].

**short summary of the study and the results!**

The datasets used for their study can be downloaded from an OSF repository [@morin2024].

# Planning the replication

## Type of replication and open science concerns

The goal of this study constitutes a replication of @morin2025's approach with the same datasets using different models. This is considered a close replication according to the following definitions: Conducting "a new study (based on work by other researchers) that is as close as possible to the original study" \[@röseler2025: Chapter 4\], with the goal to "rule out fear of the original finding being a false-positive, validate original materials or design, check generalizability/external validity for theoretically irrelevant variables (e.g., population, year of data collection)" \[@röseler2025: Chapter 4\]. The focus here is to see if the approach is generalizable to open LLMs.

During the research on replication procedures, it became clear that the terminology of replication seems to be mostly based on experiments conducted with participants, which affects the understanding of sample sizes, randomization etc. For this project, a replication of a study that leverages LLMs to assist in grammatical annotation for linguistic research, a lot of the terminology does not fit or apply. While I intend to use the same data as @morin2025, one can argue that using different models creates different data as well. Also, the models somehow represent participants in this setting, since they basically replace annotators who would otherwise do this task manually. ***maybe aufgreifen in the conclusion!*** ***entweder hier noch auf data leakage eingehen oder später*** Therefore, I had to adapt the theoretical framework as possible, and go from there. While I used the data that is provided by @morin2025, and also adapt their prompting as close as possible, achieving a very close resemblance with the original study can be difficult for multiple reasons. Among others, original studies may not include sufficient detail in some respects \[@röseler2025: Chapter 6.3\]. In the case of replicating @morin2025, the authors share their data and a transcript of the conversation, while also explaining their approach in the paper, but the code with which the automated pipeline was implemented (or even the programming language that was used, for example) is not shared. This is an important aspect to consider, since resembling the study in terms of implementing the pipeline itself is only possible to a limited extent.

In view of all these aspects, both in terms of the original study and the theoretical principles of replication, I tried to adhere to high standards of openness and transparency. This included preregistering the replication, where a detailed analysis plan, and criteria for the results to distinguish between replication success and failure, are stated [@boxleitner2026]. The preregistration was submitted to OSF before the actual analysis with the two open models was conducted.

## Planning the methodological pipeline

To plan my replication, I read the study by @morin2025 thoroughly, especially focusing on the pre-training and prompt engineering.

Further insight could be gained by going through the conversation transcript that @morin2025 provided with their data. It lists user prompts and answers of the model in a `docx.`-file. The conversation consists of the following parts:

**Pretraining**

-   First, the LLM gets a user prompt containing detailed instructions on how to classify the sentences, and is presented with examples for every instance and a step-by-step approach to classification.

-   It is instructed to look at 493 pretraining sentences in a dataset containing correct classifications, think about each classification step-by-step, and encouraged to ask questions.

**Training**

-   A round of supervised classifications follows: The model is prompted to classify the first 100 sentences (dataset: supervised_training_sketchengine_100.csv) in batches of 25. Mistakes are corrected through user prompts directly.

-   Unsupervised training round 1: After that, another dataset of 100 sentences is requested to be classified without the close supervision (and to be provided in **tab-separated** .csv-format).

-   All incorrect classifications are pasted into the next user prompt. The model is told its accuracy for the task and instructed to review the errors. **After that, the reviews are not further commented by the authors,** the model is simply told to keep those lessons in mind.

-   **Unsupervised training round 2:** It is requested to classify step-by-step and consistently apply the insertion test, then given new data (EnTenTen_random_sample_101.csv), and told to do the full classification in one batch in .csv format.

-   It is told the accuracy rate (93%) and told that it is good

**Testing**

-   Provided with new data (EnTenTen_random_sample_102.csv) and told to follow the procedure that was successfully applied in the latest round of classifications. After classification, it is again told the accuracy.

All of these steps were incorporated in the replication. With the the KI:connect API documentation [@ki:conne] and some further reading on conversations and giving previous context in prompts [@conversa], I was able to set up the LLMs for usage with an API key, and integrating the iterative processes for a multi-turn-conversation. I created a setup script that includes the API call and the basis for conversation with the LLMs. The analyses (one with each open LLM) were then conducted in separate scripts.

When looking at the datasets that @morin2025 provided in their repository, there were some minor inconsistencies I needed to take into account. The file naming was sometimes not very intuitive or informative regarding the methodological pipeline. For some training or testing rounds, the classifications done by Claude or the human annotator were provided in different files from only the sentences, for other parts of the process, there was only one file containing everything. Also, the column names varied throughout the files (for example, "Sentence" vs. "Consider-construction", or "Claude_classification" vs. "Classification_Claude"). While this would usually call for some data cleaning before running the analyses, all of these concerns were only handled programmatically in the R environment, while the files downloaded from the author's repository remained unchanged. For the data import and preprocessing of datasets I also used a separate R script.

## Piloting

Since the methodological approach proposed by @morin2025 is quite extensive and detailed, and there is no code to look into for aspects like e.g. how the datasets were implemented in the prompts, I decided to conduct a little pilot study before the actual replication, to test a similar multi-turn-conversation. This script was run and altered several times in preparation for the analysis.

I used a small dataset I had annotated manually once for another project. The task was a sentiment analysis with a lot less detailed instructions. The goal of this pilot was not to follow @morin2025's approach exactly or to achieve a high accuracy, but rather to implement and test the steps of pretraining, training and testing, make sure the model can access the datasets, and try out how well giving feedback to the models works. This made me more aware of the step-by-step process and helped me set up the pipeline for the actual study.

## LLMs

The aim of this project is to replicate the study by @morin2025 with different, and especially open LLMs. The authors used Claude Sonnet 3.5, an LLM that is known for strong performance **and often compared with ChatGPT,** including in NLP studies [@morin2025: 3].

The first model chosen for this project is Mistral Small 3.2 24B Instruct 2506, which was released in 2025 under Apache 2.0 license. It is a minor update of [Mistral-Small-3.1-24B-Instruct-2503](https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Instruct-2503), improved in the area of instruction following, repetition errors, and function calling. In this paper, it will be referred to as "Mistral".

2nd model: GPT -\> explain. This model will often simply be referred to as "GPT" in this paper.

It is important to mention that in terms of reproducibility, it would be best to use models locally [@nilsreiter2025]. Since running LLMs locally was only possible with very small LLMs due to the available hardware, I used an API key via KI:connect instead. Based onn the API documentation in [@ki:conne], **I was able to get started on chat completions.**

Even though these models are considered open source, one might always take a closer look in terms of openness: They are evidently open in some respects (open weights, for example), but closed in others (e.g. no open code) [@mistrala] **(second source!)**. Arguably, open weights are the most important aspect for reproducibility [@nilsreiter2025: 23]. While @morin2025 used a rather well-known, commercial, and closed model for their study, I want to compare this with the performance of two open ones. Mistral ... is a smaller, European model, while GPT OSS .. is an open version of ChatGPT (Ableger) and way bigger. Seeing how these two perform in comparison to the model tested in @morin2025 on a linguistic annotation task is **not just of interest for this project, but also relevant for research on LLM usage in linguistics in general.**

Considering the concern of data leakage, it is important to note that the Mistral model was released in June 2025, **and the GPT model** **in ...** @morin2025, who used data from the NOW corpus and Sketch Engine’s EnTenTen21 corpus for their study [@morin2025: 3], created their OSF-database also containing the annotated datasets used as the gold standard for comparison, in November 2024. **When and on which data the model was trained exactly is unclear, but there were definitely changes and fine-tuning on the Mistral model after the repository went public.**

## Replication criteria and hypotheses

@morin2025 present a methodological pipeline leveraging an LLM for the automatic annotation of grammatical data, based on the case study of the evaluative *consider* construction in English. Their research questions are concerned with the frequency of the different variants of the *consider* construction. While they don't formulate a hypothesis in their paper, they state a twofold goal to 1) build a replicable methodological pipeline that can be repurposed and 2) to substantially improve the quality of annotation of future corpus studies [@morin2025:3].

Keeping these concerns about the generalizability of the author's approach in mind, the present study addresses the following research question: Can the methodological pipeline proposed by @morin2025 be successfully replicated using different large language models for the same linguistic classification task?

To answer this research question, replicability needs to be measurable in this context. The authors state in their abstract to have reached "a model accuracy of over 90%" [@morin2025: 1], and lastly achieved an accuracy rate of 93% with their model. As one can see in the conversation transcript, the user prompt contains a desired accuracy level of 95% to illustrate to the model what constitutes a successful task completion.

For this project, a successful replication is defined as achieving an accuracy ≥ 90% using the original dataset and methodological pipeline proposed by @morin2025.

While attempting to reach this goal, the focus of this project - **with regard to principles of open science** - remains the replication itself, which, as mentioned before, is supposed to be as close as possible to the methodological pipeline presented in @morin2025, including specifics like

-   using XML-tags in user prompts (e.g. for \<instructions\> classification instructions \</instructions\>)

-   putting all the instruction inside user prompts (as suggested in the transcript) as opposed to implementing a system prompt

-   and so on.

Based on these considerations, the following hypothesis were established for this project:

1.  Using the methodological pipeline and dataset from @morin2025, the open model *OpenAI GPT OSS 120B* will achieve an accuracy of **at least 90%** on the linguistic classification task when evaluated against the human gold standard **in the original study.**

2.  Using the methodological pipeline and dataset from @morin2025, the open model *Mistral Small 3.2 24B Instruct 2506* will achieve an accuracy of **at least 90%** on the linguistic classification task when evaluated against the human gold standard in the **original study**.

Aside from measuring the success of the replication with a desired level of accuracy, I also wanted to analyze inter-rater agreement. While a straightforward way to do this would be to count the number of items for which annotators provide identical labels, and report that number as a percentage of the total (so-called raw or observed agreement), accidental agreement is not accounted for in this approach, which impacts reliability (and reproducibility). Instead, I wanted to utilize a coefficient from the kappa/alpha family: This is considered to measure a more meaningful agreement through involving agreement by chance, resulting in a coefficient whose value is 1 when agreement is perfect, and 0 when agreement is at chance level [@artstein2017: 299-300]. Since with LLMs it seems every more likely that some amount of agreement is by chance, it is important to account for this issue in measuring inter-rater agreement.

Two coefficients were used to measure inter-rater agreement. Cohen's κ was used for pairwise comparison, measuring agreement between two raters (each model against the human gold standard presented in the paper). Fleiss' κwas used to assess overall agreement across all annotators (Model 1, Model 2, Model 3, and the human gold standard provided in the study data). Inter-rater agreement (also referred to as inter-annotator agreement, or inter-rater reliability) is often measured for purposes like improving annotation schemes or identifying difficulties in the source [@artstein2017: 298], but in this case simply serves the purpose of drawing conclusions about which model worked "better" for annotation.

**Fleiss' kappa: suitable for comparing more than two annotators (Mistral, Claude, and human gold standard), and suitable when there are only two categories/labels** [@artstein2017: 300].

**e.g. Fleiss' Kappa** (see Larsson et al.) -\> **accounting for accidental agreement seems especially relevant in terms of LLMs, because there would be no real way of knowing if the models would simply guess.**

**Relevant** **to your field of study and/or society more broadly**

## Considering reproducibility

There was no inherent form of randomization present in this study design. Also, reproducibility in LLM studies can be tricky, especially if the models are run remotely via an API. But, making the study and the results as reproducible as possible is still an important concern, and there are certain things that can be controlled.

To enhance reproducibility, I fixed the generation parameters in the API call by setting *temperature* to 0, *top~p~* to 1, and using a constant random seed. Setting *temperature* to 0, meaning the model always chooses the most probable next token, removes random sampling and therefore makes additional constraints such as *top~k~* (sampling only from the k most probable tokens) unnecessary and potentially confounding. The number used as a random seed was derived from lotto numbers drawn on **March 25, 2026, which had not yet been disclosed at the time of pre-registration.**

Even though these measures were taken to improve reproducibility, identical outputs across runs cannot be guaranteed, as some sources of variability within the API remain outside my control.

Another thing that has to be mentioned here is the concern of **data leakage (where??)**. For my study, it is assumed that the models, functioning as several "annotators", independently label the data without knowledge of each other's work. It can only be *assumed* because there is a possibility that the models I used might have the gold standard provided in the original study as part of their training data, which would mean they would not be totally independent.

# Analysis

When I ran the replication, I tried to keep the process as close to the one shown in the transcript of the conversation in @morin2025's repository to ensure methodological consistency. **For example, while the very long initial user prompt (containing detailed instructions for step-by-step classification with examples) could also have been implemented as a system prompt in the code, I also included it in the chat, as proposed by @morin2025.**

**When importing the data that @morin2025 provided in their repository, there were some minor inconsistencies that necessitated some preprocessing** before running the replication. For example, some datasets in the repository contained only annotated versions. **Also, the authors switched the name of the column containing the sentences from "Sentences" to "Consider_construction" along the way. I extracted the relevant sentence-level input from the original files using R-based preprocessing (selecting the sentence column and renaming it to a standardized ‘Sentence’ variable). This ensured that only stimulus text (without any annotations) was provided to the model in a clean way, without altering the original data files.**

I tried to stay as close to the prompts represented by the authors' transcript as possible throughout the replication. Deviations mostly concerned specific instructions regarding the model output, for example adding "Return ONLY tab-separated values with columns: Sentence<TAB>Classification" to an otherwise similar prompt. I was careful to not alter things related to the content of the classification task. I now want to give some further insight into the analyses conducted with each model:

## Replication with GPT model

The first analysis was run with the model OpenAI GPT OSS 120B. The code used for this was mostly based on what was already tested in the pilot. Generally, the GPT run went rather smoothly, and the model seemed to be suitable for this task. I want to point out some interesting observations in regard to model behavior:

-   In the initial, very extensive instruction prompt that @morin2025 provide with their conversation transcript, there is an error at one point: "<instructions> Classify sentences containing the verb “consider” as either ‘non-evaluative’ or ‘non-evaluative’. </instructions>". Since this is what the authors provided from their conversation, I must assume this is what was they prompted to their model. With the motivation to replicate closely and get comparable results, I decided to keep the original typo and not clarify it. The GPT model pointed out this mistake in the first answer, and made clear that it must be incorrect because everything else in the prompt is centered around the contrast between 'evaluative' and 'non-evaluative'. I found this very interesting, since neither the model in the original study nor the Mistral model in the second analysis for this paper seemed to pick up on this mistake, or at least did not mention it in their answers. While this is not the focus of this paper, I think it raises interesting further questions about how models handle imperfect instructions.

-   **Another difference seen in supervised training. A sentence not understandable, (n. 100), both models deemed it incoherent/garbled, but Claude categorized it ? while GPT defaulted to non-evaluative, reasoning there was no clear instance of consider in it**

-   There was an interesting distinction during supervised training, looking at the transcript the authors provided of their conversation with Claude: When they prompted corrections, the model usually responded in terms of "You're absolutely right! Let me correct these!". GPT, while somewhat open to discussion, often stuck to its classification and explained why.

-   In all cases where I needed to compare the classifications to the ones in the datasets, I additionally specified the format: "Return ONLY tab-separated values with columns:","id<TAB>Classification". This made sense to adjust because while Claude tended to end its answers with sentences like "Please provide the new dataset and I will classify it in tab-separated .csv format.", GPT did not show this behavior, which is why I felt the need to include these informations in the prompt. This did not change the message in the prompt at all, it simply enforced that the model output was clear and comparable.

-   The accuracy level that GPT achieved in the training rounds was very high already, and interestingly, the first round of unsupervised training was better than the final one (96% in first, 93% in second round). Accuracy was rounded to two decimal points.

## Replication with Mistral model

The second analysis was run with Mistral Small 3.2 24B Instruct 2506. Overall, the model, **granted it is a lot smaller than the other two**, seemed not as well-suited for the task. I will clarify this by sharing some observations throughout the analysis:

-   As already mentioned above, Mistral did not mention the typo in the initial prompt. Instead of looking at the pretraining dataset and asking questions in case of uncertainties (as asked), it re-classified all sentences in the pretraining dataset and assigned 'non-evaluative' in 489 out of 493 cases.

-   The supervised training went a lot differently than in the first analysis (GPT) and in the conversation transcript provided about Claude. Mistral was wrong in a lot more cases, which were all corrected in the user prompts, and showed some patterns in mistakes: For the first two batches of 25 sentences, there was a strong tendency to classify constructions as 'evaluative' when they were not, though in the second half of supervised training (last 50 sentences), it was the other way around: Mistral mostly made the mistake of classifying sentences as 'non-evaluative' when they were actually 'evaluative'.

-   For the unsupervised training, the achieved accuracy in the first round was 59%, and 76% in the second round. In this case, one might argue that the model would actually need more feedback and additional rounds of training before proceeding to testing. Since the focus of this study was to replicate and not to reach a certain accuracy level, and I also needed to stay consistent with the analysis of the first model (GPT), I still proceeded to testing. While @morin2025 gave the feedback "you got a 93% accuracy! that is very good." after the last round of training, I adjusted the evaluation to the achieved accuracy level and pointed out the target that had been defined in the initial instruction prompt: "You got a 76% accuracy, which is an improvement compared to the previous round (59%). The goal remains at least 95%."

# Results

## Accuracy

The main measure for the success of this replication was the accuracy level in the testing round that could be achieved with the two open models using the methodological approach proposed by @morin2025. As mentioned in the preregistration, accuracy was calculated as follows: Accuracy = (number of correct predictions) / (total number of predictions).

|          | GPT | Mistral |
|----------|-----|---------|
| Accuracy | 94% | 67%     |

: Achieved accuracy in classification task

The hypotheses established for this project were that, using the methodological pipeline and dataset from @morin2025, the open models *OpenAI GPT OSS 120B* (Hypothesis 1) / *Mistral Small 3.2 24B Instruct 2506* (Hypothesis 2) will achieve an accuracy of **at least 90%** on the linguistic classification task when evaluated against the human gold standard in the original study.

Hypothesis 1 is therefore supported by the results presented in the table above, while hypothesis 2 is not. Although the performance of Mistral improved over the course of the training, the predefined target of at least 90% was not achieved. The model tested in the original study (Claude 3.5 Sonnet) had achieved an accuracy level of 93% [@morin2025: 6].

GPT reached **0.9411765** accuracy. (rounded to 94%))

## Inter-rater agreement

### Cohen's κ

|           | GPT   | Mistral | Claude (original study) |
|-----------|-------|---------|-------------------------|
| Cohen's κ | 0.877 | 0.173   | 0.857                   |

: Inter-rater agreement of each model in comparison with the human gold standard

Cohen's κ was calculated for pairwise comparisons (each model against the human gold standard provided in the original study data). Basen on the accuracy levels, it not surprising that GPT shows a similarly high Cohen's κ value than Claude in the original study. According to the benchmarks put forth by [@landis1977: 165], the strength of agreement in both GPT and Claude would be interpreted as "almost perfect". Mistral on the other hand shows a very low κ coefficient, which would only be ranked a "slight" strength of agreement after @landis1977. To investigate this result further, I want to provide a closer look at the Cohen's κ measures for Mistral:

```         
 Cohen's Kappa for 2 Raters (Weights: unweighted)   Subjects = 102     Raters = 2      Kappa = 0.173           z = 2.56    p-value = 0.0106 
```

I explicitly want to focus on the p-value here. While the κ coefficient measures **how strong** the agreement is, the p-value measures if there is any agreement beyond chance. For the other two models, the p-value reported in the output of the Cohen's κ function was 0. In the case of Mistral, it is slightly higher, but still under 0.05, indicating statistical significance. This means that agreement is better than chance, but still very low.

**Rest: exact values:**

For Cohen's kappa (IRR between **GPT** and HGS):

Cohen's Kappa for 2 Raters (Weights: unweighted)

Subjects = 102 Raters = 2 Kappa = 0.877 z = 8.86 p-value = 0

-\> (**interpret with Landig scale - citation**)

Cohen's kappa (**Mistral** and HGS)\
Cohen's Kappa for 2 Raters (Weights: unweighted) Subjects = 102 Raters = 2 Kappa = 0.173 z = 2.56 p-value = 0.0106

Cohen's kappa (**Claude** and HGS):

```         
print(cohens_kappa_claude_human)  Cohen's Kappa for 2 Raters (Weights: unweighted)   Subjects = 102     Raters = 2      Kappa = 0.857           z = 8.67    p-value = 0 
```

Replication focus: Hypothesis, was the replication successful?

### Fleiss' κ

Fleiss' κ was calculated to measure overall agreement between all four raters. With a value of κ = 0.517, this constitutes a "moderate" agreement.

```         
 Fleiss' Kappa for m Raters   Subjects = 102     Raters = 4      Kappa = 0.517           z = 12.8    p-value = 0
```

## maybe: addition about data leakage

# Discussion of outcomes in light of differences

is the approach indeed replicable? -\> things like: there is no code or any information on how the pipeline was actually implemented and automated. That would have been really helpful, or would be helpful for further studies. Also, looking at the trnascript, some things were not really consistent. For example, while instructions were supposed to always be given in XML-tags, this was not used in between (e.g. "next batch" etc., see transcript).

For the unsupervised training, @morin2025 ran two rounds. In their paper it is mentioned that this "iterative training and validation cycle was repeated until Claude achieved the desired level of accuracy, with each round of classifications always providing unseen data" [@morin2025: 6]. Since I wanted to replicate this study with the exact same data, I could not exactly follow this part, as I would have stopped after the second round of unsupervised training, even if the model would not have reached a high accuracy level.

Relevance!

Generalizability, Opportunities

point out how the terminology and study design is not suited yet for these kinds of studies

# Reflection of methodological approach and difficulties

# Conclusion

How do open LLMs perform in comparison and why is it crucial that we support and optimize them?
